Repository wooga/atlas-plugins, pull requests merged in 2021-06, with the labels that each got.

#51 Update gradle to 6.9
  README.md
  gradle/wrapper/gradle-wrapper.properties
  gradle_check_versions.sh
Labels: atlas-stream, gradle, update

#52 Add SonarQube plugin
  .gitignore
  build.gradle
  src/integrationTest/groovy/wooga/gradle/plugins/PluginsPluginIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/plugins/PluginsPlugin.groovy
  src/test/groovy/wooga/gradle/plugins/PluginsPluginActivationSpec.groovy
  src/test/groovy/wooga/gradle/plugins/PluginsPluginSpec.groovy
Labels: add, atlas-stream

#54 Add sonar defaults from github
  src/main/groovy/wooga/gradle/plugins/PluginsPlugin.groovy
  src/main/groovy/wooga/gradle/plugins/sonarqube/PropertyFactory.groovy
  src/main/groovy/wooga/gradle/plugins/sonarqube/RepositoryInfo.groovy
  src/main/groovy/wooga/gradle/plugins/sonarqube/SonarQubeConfiguration.groovy
  src/test/groovy/wooga/gradle/plugins/PluginsPluginSpec.groovy
Labels: add, atlas-stream

#57 Sonar integration and fixes
  Jenkinsfile
  build.gradle
  src/main/groovy/wooga/gradle/plugins/PluginsPlugin.groovy
  src/main/groovy/wooga/gradle/plugins/sonarqube/SonarQubeConfiguration.groovy
  src/test/groovy/wooga/gradle/plugins/PluginsPluginSpec.groovy
Labels: add, atlas-stream, change, fix
