Repository wooga/atlas-plugins, pull requests merged in 2021-09, with the labels that each got.

#69 Small fixes for issues #67 and #68
  src/integrationTest/groovy/wooga/gradle/plugins/PluginsPluginIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/plugins/PluginsPlugin.groovy
Labels: fix, atlas-stream

#65 Force groovy modules to version of version shipped with gradle
  build.gradle
  src/main/groovy/wooga/gradle/plugins/PluginsPlugin.groovy
  src/test/groovy/wooga/gradle/plugins/PluginsPluginSpec.groovy
Labels: improve, atlas-stream

#75 Configuration avoidance API and branch name inference
  src/integrationTest/groovy/wooga/gradle/plugins/PluginsPluginIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/plugins/PluginsPlugin.groovy
  src/main/groovy/wooga/gradle/plugins/sonarqube/RepositoryInfo.groovy
  src/main/groovy/wooga/gradle/plugins/sonarqube/SonarQubeConfiguration.groovy
  src/test/groovy/wooga/gradle/plugins/PluginsPluginSpec.groovy
Labels: improve, add, atlas-stream
